import Head from 'next/head'
import Showcase from '../components/PageShowcase/Showcase'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Learn Coding Today!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Showcase/>
    </div>
  )
}
